name: LilysPermissions
version: 1.0.0
description: permissions and chat formatting made simple
author: DelilahEve
main: io.delilaheve.LilysPermissions
commands:
  promote:
    description: promote a user within a ladder
    usage: /promote <user> [ladder]
  demote:
    description: demote a user within a ladder
    usage: /demote <user> [ladder]
permissions:
  lilys_permissions.*:
    children:
      lilys_permissions.promote:
        description: Permits use of the /promote command
        default: op
      lilys_permissions.demote:
        description: Permits use of the /demote command
        default: op